export const AUTH_EMAIL_SIGN_UP_REQUEST = '@auth/EMAIL_SIGN_UP_REQUEST';
export const AUTH_EMAIL_SIGN_UP_SUCCESS = '@auth/EMAIL_SIGN_UP_SUCCESS';
export const AUTH_EMAIL_SIGN_UP_FAILED = '@auth/EMAIL_SIGN_UP_FAILED';

export const AUTH_EMAIL_LOGIN_REQUEST = '@auth/EMAIL_LOGIN_REQUEST';
export const AUTH_EMAIL_LOGIN_SUCCESS = '@auth/EMAIL_LOGIN_SUCCESS';
export const AUTH_EMAIL_LOGIN_FAILED = '@auth/EMAIL_LOGIN_FAILED';
